/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "secondary-container": "#6cf8bb",
              "on-secondary-fixed-variant": "#005236",
              "on-secondary-fixed": "#002113",
              "background": "#f7f9fb",
              "primary-container": "#2563eb",
              "surface-dim": "#d8dadc",
              "surface-container-low": "#f2f4f6",
              "secondary-fixed-dim": "#4edea3",
              "outline-variant": "#c3c6d7",
              "on-surface": "#191c1e",
              "surface-tint": "#0053db",
              "on-secondary-container": "#00714d",
              "inverse-on-surface": "#eff1f3",
              "on-primary-fixed-variant": "#003ea8",
              "outline": "#737686",
              "inverse-surface": "#2d3133",
              "tertiary-container": "#64706e",
              "on-primary-fixed": "#00174b",
              "on-error": "#ffffff",
              "tertiary": "#4b5856",
              "secondary-fixed": "#6ffbbe",
              "on-primary-container": "#eeefff",
              "surface": "#f7f9fb",
              "surface-container-high": "#e6e8ea",
              "tertiary-fixed-dim": "#bcc9c6",
              "on-tertiary": "#ffffff",
              "primary-fixed-dim": "#b4c5ff",
              "surface-container": "#eceef0",
              "on-primary": "#ffffff",
              "surface-container-highest": "#e0e3e5",
              "primary": "#004ac6",
              "on-tertiary-fixed": "#121e1c",
              "on-tertiary-container": "#e6f3f1",
              "primary-fixed": "#dbe1ff",
              "surface-variant": "#e0e3e5",
              "error-container": "#ffdad6",
              "on-tertiary-fixed-variant": "#3d4947",
              "tertiary-fixed": "#d8e5e2",
              "on-error-container": "#93000a",
              "inverse-primary": "#b4c5ff",
              "on-background": "#191c1e",
              "secondary": "#006c49",
              "surface-container-lowest": "#ffffff",
              "on-secondary": "#ffffff",
              "error": "#ba1a1a",
              "surface-bright": "#f7f9fb",
              "on-surface-variant": "#434655"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "lg": "24px",
              "xl": "40px",
              "gutter": "16px",
              "sm": "8px",
              "max_width": "1200px",
              "md": "16px",
              "xs": "4px",
              "margin": "24px",
              "unit": "4px"
      },
      "fontFamily": {
              "body-sm": ["Inter", "sans-serif"],
              "body-md": ["Inter", "sans-serif"],
              "headline-md": ["Plus Jakarta Sans", "sans-serif"],
              "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
              "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
              "body-lg": ["Inter", "sans-serif"],
              "label-caps": ["Inter", "sans-serif"]
      },
      "fontSize": {
              "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
              "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
              "headline-sm": ["20px", {"lineHeight": "1.4", "fontWeight": "600"}],
              "headline-lg": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
              "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "label-caps": ["12px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
